#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
SENDER_INIT="/usr/bin/autod"

start_service() {
        if [ -x $SENDER_INIT ]; then
                procd_open_instance autod
                procd_set_param command $SENDER_INIT /etc/autod.conf
                procd_set_param respawn
                procd_set_param stdout 1
                procd_set_param stderr 1
                procd_close_instance
        fi
}
